/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.u1a8_edmondliang;

/**
 *
 * @author edmon
 */
public class U1A8_EdmondLiang extends javax.swing.JFrame {

    /** Creates new form U1A8_EdmondLiang */
    public U1A8_EdmondLiang() {
        initComponents();
        tareaarray.setEditable(false);
        // Makes the text area unable to be edited by the user
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsumalltheoddnum = new javax.swing.JButton();
        btnsumalltheevennum = new javax.swing.JButton();
        lblsum = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnexitapp = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        txtinput = new javax.swing.JTextField();
        btnadding = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        btnremoveinteger = new javax.swing.JButton();
        ScrollPane = new javax.swing.JScrollPane();
        tareaarray = new javax.swing.JTextArea();
        btnsumallnum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnsumalltheoddnum.setText("Sum Odd");
        btnsumalltheoddnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumalltheoddnumActionPerformed(evt);
            }
        });

        btnsumalltheevennum.setText("Sum Even");
        btnsumalltheevennum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumalltheevennumActionPerformed(evt);
            }
        });

        lblsum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbl1.setText("Integer Sums");

        btnexitapp.setText("Exit");
        btnexitapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitappActionPerformed(evt);
            }
        });

        lbl2.setText("Enter an integer:");

        txtinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinputActionPerformed(evt);
            }
        });

        btnadding.setText("Add");
        btnadding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddingActionPerformed(evt);
            }
        });

        btnlist.setText("List");
        btnlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistActionPerformed(evt);
            }
        });

        btnremoveinteger.setText("Remove");
        btnremoveinteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveintegerActionPerformed(evt);
            }
        });

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tareaarray.setColumns(20);
        tareaarray.setRows(5);
        ScrollPane.setViewportView(tareaarray);

        btnsumallnum.setText("Sum All");
        btnsumallnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumallnumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbl1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsum, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnsumalltheoddnum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnsumallnum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnsumalltheevennum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnexitapp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnlist)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnremoveinteger)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnadding)))
                                                .addGap(1, 1, 1)))
                                        .addGap(77, 77, 77)))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(btnadding)
                    .addComponent(txtinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnremoveinteger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnsumallnum)
                        .addGap(18, 18, 18)
                        .addComponent(btnsumalltheevennum)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsumalltheoddnum)
                            .addComponent(btnexitapp)))
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblsum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String[] Integerarry = new String[20];
    // make the array with the storage of 20
    
    private void btnsumalltheoddnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumalltheoddnumActionPerformed
        int oddsum = 0;
        // Iterate through the array to calculate the sum of odd numbers
        for (int i=0; i<Integerarry.length; i++){
            if (Integerarry[i]!=null&&Integer.parseInt(Integerarry[i]) % 2 != 0){
                // Adds the value of the current index of the array to the sum if it is odd
                oddsum += Integer.parseInt(Integerarry[i]);
            }
        }
        lblsum.setText("The sum of all odd number is "+oddsum);
        // Displays the sum
    }//GEN-LAST:event_btnsumalltheoddnumActionPerformed

    private void btnsumalltheevennumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumalltheevennumActionPerformed
        int evensum = 0;
        // Iterate through the array to calculate the sum of even numbers

        for (int i=0; i<Integerarry.length; i++){
            if (Integerarry[i]!=null&&Integer.parseInt(Integerarry[i]) % 2 == 0){
                // Adds the value of the current index of the array to the sum if it is even
                evensum += Integer.parseInt(Integerarry[i]);
            }
        }
        // Displays the sum
        lblsum.setText("The sum of all even number is "+evensum);
    }//GEN-LAST:event_btnsumalltheevennumActionPerformed

    private void btnexitappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitappActionPerformed
        System.exit(0);
        // Closes the app
    }//GEN-LAST:event_btnexitappActionPerformed

    private void txtinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinputActionPerformed

    private void btnaddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddingActionPerformed
        try{
            // Try to add the entered integer to the array
            if (Integer.parseInt(txtinput.getText())>=0){
            // Make sure that the user's input is a positive integer
                for (int i=0; i<Integerarry.length; i++){
                    // A for loop to iterate through the array
                    if (Integerarry[i] == null){
                    // If the array at this index is equal to null (empty), replace it with the user's integer
                        Integerarry[i] = txtinput.getText();
                        break;
                    }
                    if (i==19){
                    // If there is no empty slot, display a message
                        lblsum.setText("You have reached the maximum amount of number");
                    }
                }
            }
            else{
                // If the entered integer is less than 0, display an error message
                lblsum.setText("Invalid entry, please enter an integer greater than 0");
            }
        }
        catch (NumberFormatException e){
            // If the user enters anything other than a number, display an error message
            lblsum.setText("Invalid entry, please enter an integer greater than 0");
        }
    }//GEN-LAST:event_btnaddingActionPerformed

    private void btnlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistActionPerformed
        tareaarray.setText("");
        // Resets the array display
        for (int i=0; i<Integerarry.length; i++){
            // Iterates through the length of the array
            if (Integerarry[i]==null){
                continue;
                // Skip empty slots in the array
            }
            tareaarray.setText(tareaarray.getText()+Integerarry[i]+"\n");
            // Append the current index of the array to the text area
        }
        for (int i=0; i<Integerarry.length; i++){
            // Iterate through the length of the array
            if (Integerarry[i]==null){
                continue;
                // Skip empty slots in the array
            }
            if (i==0){
            // If it is the first integer, no comma will precede it
                lblsum.setText(Integerarry[i]);
            }
            else{
                lblsum.setText(lblsum.getText()+", "+Integerarry[i]);
            }
            // Display a comma-separated list of array number
        }
    }//GEN-LAST:event_btnlistActionPerformed

    private void btnremoveintegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveintegerActionPerformed
        try{
            // Try to remove the specified integer from the array
            for (int i=Integerarry.length-1; i>-1; i--){
                // Iterate through the array in reverse order
                if (Integerarry[i]==null){
                    // Skip the iteration if the index is empty
                    continue;
                }
                if (Integer.parseInt(Integerarry[i]) == Integer.parseInt(txtinput.getText())){
                // If the array at the index is equal to the user's integer, set it to null
                    Integerarry[i] = null;
                    for (int l=i; l<Integerarry.length-1;l++){
                        if (Integerarry[l+1]!=null){
                            Integerarry[l] = Integerarry[l+1];
                            Integerarry[l+1] = null;
                        }
                        // Move the newly made empty index to the end with the other empty slots
                    }
                    break;
                }
                if (i==0){
                // If the for loop reaches the last iteration without finding the user's integer, display a message
                    lblsum.setText("Integer not found within list");
                }
            }
        }
        catch (NumberFormatException e){
            // If the user enters anything other than a number, display an error message
            lblsum.setText("Invalid entry, please enter an integer greater than 0");
        }
    }//GEN-LAST:event_btnremoveintegerActionPerformed

    private void btnsumallnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumallnumActionPerformed
        int sum = 0;
        // Iterate through the array to calculate the sum of all number
        for (int i=0; i<Integerarry.length; i++){
            // Add the value of the current index of the array to the sum
            if (Integerarry[i] != null){
                sum += Integer.parseInt(Integerarry[i]);
            }
        }
        lblsum.setText("The sum of all number is "+sum);
        // Display the total sum of all number
    }//GEN-LAST:event_btnsumallnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A8_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A8_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A8_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A8_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A8_EdmondLiang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnadding;
    private javax.swing.JButton btnexitapp;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnremoveinteger;
    private javax.swing.JButton btnsumallnum;
    private javax.swing.JButton btnsumalltheevennum;
    private javax.swing.JButton btnsumalltheoddnum;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblsum;
    private javax.swing.JTextArea tareaarray;
    private javax.swing.JTextField txtinput;
    // End of variables declaration//GEN-END:variables

}
